{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "5cd99dcf_0bc10fd8",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2022-01-13T20:45:20Z",
      "side": 1,
      "message": "What does this script do? I can\u0027t find it anywhere in AOSP",
      "range": {
        "startLine": 12,
        "startChar": 5,
        "endLine": 12,
        "endChar": 32
      },
      "revId": "16f120fb152835428f07f6030fedcc9d6826375f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "97fb825c_b31667e9",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1081223
      },
      "writtenOn": "2022-01-13T20:49:07Z",
      "side": 1,
      "message": "bootable/recovery/updater_sample/tools/gen_update_config.py\nSorry, should\u0027ve used full path, probably forgot to edit commit msg\nIt\u0027s used by SystemUpdaterSample to generate configs that should be passed to the updater app",
      "parentUuid": "5cd99dcf_0bc10fd8",
      "range": {
        "startLine": 12,
        "startChar": 5,
        "endLine": 12,
        "endChar": 32
      },
      "revId": "16f120fb152835428f07f6030fedcc9d6826375f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8186a20c_2491b618",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1081223
      },
      "writtenOn": "2021-11-03T16:16:11Z",
      "side": 1,
      "message": "I\u0027m not sure if this is needed by anything _real_ out there ( aside me ), but I was trying the updater_sample with an OTA from R and hit this issue.\nIs this fine by you?",
      "revId": "16f120fb152835428f07f6030fedcc9d6826375f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "492e4c41_1767b9a6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2022-01-13T20:43:45Z",
      "side": 1,
      "message": "If you are using S releasetools script to generate OTA for R, then the S script should automatically generate metadata proto? The code to generate metadata proto and the code to check them are added at the same time(they are both in ota_utils.py). How can you run into an issue where package doesn\u0027t have metadata proto but your ota script tries to find it?",
      "revId": "16f120fb152835428f07f6030fedcc9d6826375f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "54915e31_029107fc",
        "filename": "tools/releasetools/ota_utils.py",
        "patchSetId": 1
      },
      "lineNbr": 573,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2022-01-18T18:13:46Z",
      "side": 1,
      "message": "I would rather check if METADATA_PROTO_NAME is in zip_file first before calling ComputeEntryOffsetSize. Relying on exceptions is too fuzzy.",
      "range": {
        "startLine": 573,
        "startChar": 0,
        "endLine": 573,
        "endChar": 68
      },
      "revId": "16f120fb152835428f07f6030fedcc9d6826375f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}