{
  "comments": [
    {
      "key": {
        "uuid": "48e70357_5a50f531",
        "filename": "tools/releasetools/add_img_to_target_files.py",
        "patchSetId": 5
      },
      "lineNbr": 25,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2016-08-24T19:48:29Z",
      "side": 1,
      "message": "typo",
      "range": {
        "startLine": 25,
        "startChar": 10,
        "endLine": 25,
        "endChar": 19
      },
      "revId": "4d0cea005fc9995248190903bc6bcc290b978ea6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "48e70357_fa6909c7",
        "filename": "tools/releasetools/add_img_to_target_files.py",
        "patchSetId": 5
      },
      "lineNbr": 29,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2016-08-24T19:48:29Z",
      "side": 1,
      "message": "Rebuild the recovery patch and write it to the system image. Only meaningful when system image needs to be rebuilt.",
      "range": {
        "startLine": 29,
        "startChar": 6,
        "endLine": 29,
        "endChar": 35
      },
      "revId": "4d0cea005fc9995248190903bc6bcc290b978ea6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "48e70357_9a59dd37",
        "filename": "tools/releasetools/add_img_to_target_files.py",
        "patchSetId": 5
      },
      "lineNbr": 44,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2016-08-24T19:48:29Z",
      "side": 1,
      "message": "typo",
      "range": {
        "startLine": 44,
        "startChar": 6,
        "endLine": 44,
        "endChar": 13
      },
      "revId": "4d0cea005fc9995248190903bc6bcc290b978ea6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}