{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "c09d9826_9fff72da",
        "filename": "tools/releasetools/check_target_files_signatures.py",
        "patchSetId": 2
      },
      "lineNbr": 532,
      "author": {
        "id": 1018026
      },
      "writtenOn": "2022-01-14T15:24:37Z",
      "side": 0,
      "message": "I dont think we should remove this - it is a valid error condition and no one goes back and looks at logs once signed artifacts are generated.",
      "range": {
        "startLine": 532,
        "startChar": 8,
        "endLine": 532,
        "endChar": 12
      },
      "revId": "9e81c4487532a2004df5e37d77d66c55ba07a154",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}