{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "49b3d3c1_2ce77925",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-16T17:45:19Z",
      "side": 1,
      "message": "CheckSize should already handle the case of missing keys, is this really needed?",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e067b979_2f2bc84e",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 2052331
      },
      "writtenOn": "2023-10-19T06:21:09Z",
      "side": 1,
      "message": "Without these changes hitting below compilation Error, So need to convert a real number \n\nTraceback (most recent call last):\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/__main__.py\", line 12, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1335, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1312, in main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 596, in GenerateNonAbOtaPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 244, in WriteFullOTAPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/common.py\", line 2427, in CheckSize\nTypeError: %d format: a real number is required, not str",
      "parentUuid": "49b3d3c1_2ce77925",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bd2ed062_645a940e",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-23T18:00:30Z",
      "side": 1,
      "message": "Change \n\n```\n    limit \u003d info_dict.get(device + \"_size\")\n```\n\nto\n\n```\n    limit \u003d int(info_dict.get(device + \"_size\", 0))\n```\n\nin `CheckSize`\n\nThen you don\u0027t need to hard code partition names here",
      "parentUuid": "e067b979_2f2bc84e",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}