{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "bc898337_29c6418a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1121894
      },
      "writtenOn": "2021-04-05T18:38:18Z",
      "side": 1,
      "message": "Kelvin, this failed the unit tests, can you look into it.\n\nI am chasing separately why TH forgave the issues.... But if you open the result from TH you can see the failures.",
      "revId": "c184fa1887df633645e85570c06428cd97671fc8",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}